steps:
- name: 'gcr.io/cloud-builders/git'
 args: ['clone', 'https://github.com/harshmalviya2023/dataflowPipeline.git', '.']
- name: 'gcr.io/cloud-builders/mvn'
 args: ['package']
- name: 'gcr.io/cloud-builders/gsutil'
 args: ['cp', 'target/myjar.jar', 'gs://dataset2023/myjar.jar']
